### ISSUE TITLE
SysAdm should offer display-related preferences

### ISSUE THREAD

**Issue by grahamperrin** [trueos/sysadm#23]
**At least**

Allow the user to: 
- add a screen
- set resolutions
- position screens in relation to each other
- remove a screen. 

**Plus, ideally**

Allow the user to manually prefer a driver. An example use case: 
- automation causes use of VESA; and 
- the user knows that SCFB will be more appropriate.

**Comment by kmoore134** [comment]
This issue was moved to trueos/trueos-core#79
