### ISSUE TITLE
sysadm is a PITA and likes to close itself

### ISSUE THREAD

**Issue by Mrt134** [trueos/sysadm#29]
_From @JoshDW19 on October 17, 2017 14:45_

I don't know if my mouse is incredibly sensitive or what, but when I try to right or left click sysadm's icon in the bottom right of my screen I have a 50/50 chance of closing the client because the "Close Sysadm Client" button appears right underneath the cursor. This leads to much rage. :)

_Copied from original issue: trueos/trueos-core#1488_

**Comment by q5sys** [comment]
By any chance have you tried with a different mouse just to remove the possibility that it is not a hardware issue?  It almost sounds like your mouse is double clicking during a single click.  Or that you've had to much caffeine and your trigger finger is a bit twitchy. ;)

**Comment by JoshDW19** [comment]
I just did a very scientific test and tried to click the sysadm icon on my laptop. I single click the sysadm icon and when I let go of the button it just closes. Try holding down the left mouse button a half second longer than you normally would and let go. Confirmed bug because science.

**Comment by beanpole135** [comment]
Fixed.

https://github.com/trueos/sysadm-ui-qt/commit/93e57c605ff7f15cf64f4e2d86ef2fd4683897e4
